### ISSUE TITLE
New version of HTTPClient not checking connections causing problems

### ISSUE THREAD

**Issue by lloydmeta** [m3dev/octoparts#125]
The bump to [version 4.4](https://github.com/m3dev/octoparts/commit/5024f513caf2796725eefabe4b231dafc10bcb84) of HTTPClient brought in new behaviour for `PoolingHttpClientConnectionManager`, namely

> The handling of stale connections was changed in version 4.4. Previously, the code would check every connection by default before re-using it. The code now only checks the connection if the elapsed time since the last use of the connection exceeds the timeout that has been set. The default timeout is set to 5000ms

This is causing problems such as the following:

```
Caused by NoHttpResponseException
blah.com:80 failed to respond

org.apache.http.impl.conn.DefaultHttpResponseParser in parseHead at line 143 (application)
org.apache.http.impl.conn.DefaultHttpResponseParser in parseHead at line 57 (application)
org.apache.http.impl.io.AbstractMessageParser in parse at line 261 (application)
org.apache.http.impl.DefaultBHttpClientConnection in receiveResponseHeader at line 165 (application)
org.apache.http.impl.conn.CPoolProxy in receiveResponseHeader at line 167 (application)
org.apache.http.protocol.HttpRequestExecutor in doReceiveResponse at line 272 (application)
org.apache.http.protocol.HttpRequestExecutor in execute at line 124 (application)
com.m3.octoparts.http.InstrumentedHttpClient$InstrumentedHttpRequestExecutor in execute at line 126 (application)
org.apache.http.impl.execchain.MainClientExec in execute at line 271 (application)
org.apache.http.impl.execchain.ProtocolExec in execute at line 184 (application)
org.apache.http.impl.execchain.RetryExec in execute at line 88 (application)
org.apache.http.impl.execchain.RedirectExec in execute at line 110 (application)
Frames 12 until 19 were omitted and not available.
com.m3.octoparts.aggregator.handler.HttpPartRequestHandler$$anon$1 in retrieve at line 85 (application)
com.m3.octoparts.aggregator.handler.HttpPartRequestHandler$$anonfun$process$1$$anonfun$apply$1 in apply at line 63 (application)
com.m3.octoparts.aggregator.handler.HttpPartRequestHandler$$anonfun$process$1$$anonfun$apply$1 in apply at line 63 (application)
com.m3.octoparts.hystrix.HystrixExecutor$$anon$1 in run at line 24 (application)
com.netflix.hystrix.HystrixCommand in executeCommand at line 1279 (application)
Caused by HystrixRuntimeException
medqa:topicByConferenceId failed and fallback disabled.

com.netflix.hystrix.HystrixCommand in getFallbackOrThrowException at line 1677 (application)
com.netflix.hystrix.HystrixCommand in executeCommand at line 1350 (application)
com.netflix.hystrix.HystrixCommand in access$2200 at line 105 (application)
com.netflix.hystrix.HystrixCommand$5 in call at line 1186 (application)
com.netflix.hystrix.strategy.concurrency.HystrixContextCallable in call at line 51 (application)
```

I imagine this is caused by the server not setting a proper keep alive and/or the new pool not actually caring to check if the connection is still valid; so when the server kills the connection and we try to re-use it, we run into `NoHttpResponseException`.

In order to fix this, I think we either have to pass a timeToLive as a constructor argument to  `PoolingHttpClientConnectionManager` or call `setValidateAfterInactivity`.

**Comment by mauhiz** [comment]
#126 did not help, then fixed by #128

**Comment by okapies** [comment]
It seems the issue #128 has been resolved in httpcore 4.4.6. https://issues.apache.org/jira/browse/HTTPCORE-433

**Comment by aronsinoaifw** [comment]
Using 4.5 and the problem is still there

**Comment by shatk** [comment]
Still getting NoHttpResponseException  with  4.5.7  as well as 4.5.10 .  Anyone got a work around ?
